### ISSUE TITLE
Add Frontmatter for Interviewee/Interviewer and Quotation Styling for Blog Posts

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5882]
### Current Behavior
This issue is for tracking two enhancements for the upcoming interview-style blog posts on [Layer5.io](https://layer5.io). These enhancements aim to improve the internal references in frontmatter and apply styling to interviewee responses.

### **Enhancements**

1. **Frontmatter Additions:**
   - Add two new frontmatter items: `interviewee` and `interviewer`.
   - These fields will serve as internal references for the blog posts but will not be displayed on the front-end.

2. **CSS Quotation Styling:**
   - Automatically wrap interviewee responses in quotation marks using CSS pseudo-selectors (`::before` and `::after`).
   - The interviewee’s responses should be wrapped in opening and closing quotes to improve readability and maintain a consistent style across all posts.

### **Tasks**
- [ ] Add new frontmatter fields for `interviewee` and `interviewer`.
- [ ] Ensure these fields are only internal references and are not displayed in the blog post content.
- [ ] Use CSS to wrap interviewee responses with quotation marks using pseudo-selectors.
- [ ] Test to ensure consistency across various blog posts.

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Sumit2997** [comment]
Hi @Ashparshp ,I would like to work on this issue, can you please assign it to me?

**Comment by Ashparshp** [comment]
@Sumit2997, Go ahead...

**Comment by Ashparshp** [comment]
@Sumit2997, working on it?

**Comment by Sumit2997** [comment]
@Ashparshp, yes I am working on it, I will be raising a PR by tomorrow.
