### ISSUE TITLE
[NG] Add multiple news articles to the layer5-ng site

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#815]
**Current Behavior**
The [news pages ](https://layer5ng.netlify.app/news/) of the layer5-ng site contains one news article currently

**Desired Behavior**
Add the rest of the news articles. Data to be added are in [this folder](https://github.com/layer5io/layer5/tree/master/collections/_news). The current news page is [here](https://layer5.io/news). The news article are present for layer5ng [here](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/news). A sample news article has been added for reference. 

Multiple contributors can work on this and make individual PRs. 

The news articles to be added are - 

- [x] Layer5 and HashiCorp Launch Service Mesh Partnership

- [x] The New Stack: What the Numbers Say about How Service Meshes Are Used Today

- [x] Learn Cloud Native: Managing service meshes with Meshery

- [x] Vendors make a splash in 2019 service mesh implementation rush

- [x] The New Stack: Meshery in top 3 service mesh developments in 2020

- [x] Enterprise Networking Planet: CNCF SIG Network Set to Push Cloud Native Networking Forward

- [x] KubeCon NA: CNCF SIG Network Set Intro and Deep-Dive

- [x] Layer5 Joins the CNCF

- [x] Forrester: Layer5 and Meshery Help Developers Focus On The Business

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
I would like to work on this

**Comment by Tanuj22** [comment]
@lolyparty Please go ahead. You can send PRs one at a time for each of the news articles :)

**Comment by leecalcote** [comment]
Iterative web programming. :)

**Comment by jomefavourite** [comment]
I'll try my best

**Comment by lolyparty** [comment]
@jomefavourite can we work on this together?

**Comment by jomefavourite** [comment]
@lolyparty Sure

**Comment by lolyparty** [comment]
> @lolyparty Sure

I'll hit you up on slack

**Comment by jomefavourite** [comment]
@leecalcote I have a question, if I had already cloned the master branch, do I have to clone the layer5-ng too

**Comment by jomefavourite** [comment]
@lolyparty do u know Gatsby,  cause looking at the files is daunting.

**Comment by lolyparty** [comment]
> @lolyparty do u know Gatsby, cause looking at the files is daunting.

No, the tag on the issue says react which I'm into

**Comment by jomefavourite** [comment]
okay, have you cloned the repo?

**Comment by lolyparty** [comment]
> okay, have you cloned the repo?

No, I haven't my laptop is dead right now,  but I've  forked the repo

**Comment by jomefavourite** [comment]
Okay

**Comment by jomefavourite** [comment]
I'm still trying to figure out what to do

**Comment by lolyparty** [comment]
> I'm still trying to figure out what to do

I'll send you a message on slack when I'm online

**Comment by jomefavourite** [comment]
@Tanuj22 could you please point out where news layout is on the repo

**Comment by Jashpatel1** [comment]
> @Tanuj22 could you please point out where news layout is on the repo

The [news section for layer5](https://github.com/layer5io/layer5/tree/master/collections/_news) is present here. And the [news section for layer5-ng](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/news) is present here.

**Comment by chandrashritii** [comment]
@Tanuj22 The multiple news articles can be separated into individual issues for different contributors to take up.

**Comment by Tanuj22** [comment]
@jomefavourite @lolyparty This issue has been broken you smaller sub-issues. I am assigning you each of you one of them :)

**Comment by leecalcote** [comment]
@Tanuj22 that is most helpful. 👍

**Comment by jomefavourite** [comment]
Okay @Tanuj22

**Comment by lolyparty** [comment]
> Okay @Tanuj22

Have you been able to setup your development environment?

**Comment by jomefavourite** [comment]
Yes @lolyparty

**Comment by jomefavourite** [comment]
Could you please put me through the process @lolyparty

**Comment by lolyparty** [comment]
> Could you please put me through the process @lolyparty

I sent you a message on slack

**Comment by jomefavourite** [comment]
Hello, since my issue has been merged should I unassign myself?

**Comment by leecalcote** [comment]
@jomefavourite, if each of the news articles in the checklist have been migrated, we can close this issue.

**Comment by lolyparty** [comment]
> Hello, since my issue has been merged should I unassign myself?

Hey Josh, you can leave it.

**Comment by jomefavourite** [comment]
I noticed that the news I added isn't showing here, hope I didn't do something wrong?
![Screenshot_20201015-175858_Samsung Internet](https://user-images.githubusercontent.com/54733225/96162454-79114380-0f10-11eb-9738-19ec3d6df84a.jpg)

**Comment by jomefavourite** [comment]
> @jomefavourite, if each of the news articles in the checklist have been migrated, we can close this issue. 

Okay

**Comment by Tanuj22** [comment]
@jomefavourite actually the netlify deployment is stoped currently that's the reason it's not showing

**Comment by jomefavourite** [comment]
Okay then, no problem

**Comment by Tanuj22** [comment]
Closing as all news articles have been migrated :)
